name: Release

on:
  push:
    branches:
       -main

jobs:
  build:

    runs-on: ubuntu.22.04

    steps:
    - name: checkout repository
      uses: actions/checkout@v4
    - name: Set git identity
      run: |
          git config --global user.email "correo"
          git config --global user.name "name"
        python-version:${{ matrix.python-version }}
    - name: Set up python
      uses: actions/set-up-python@v4
      with:
         python-version: 3.10.12
    - name: create release
      run: |
        git tag -a ${{ github.run_number }} -m "Release v${{ github.run_number }}"
        git push origin v${{ github.run_number }}
